In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"matches.csv")
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [3]:
df2 = pd.read_csv(r"deliveries.csv")
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

# Data Exploration

In [4]:
df1.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [5]:
df2.head(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

In [6]:
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [7]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [8]:
df1.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [9]:
df2.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [10]:
df1['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [11]:
df2['extras_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [12]:
df1.nunique()

id                 1095
season               17
city                 36
date                823
match_type            8
player_of_match     291
venue                58
team1                19
team2                19
toss_winner          19
toss_decision         2
winner               19
result                4
result_margin        98
target_runs         170
target_overs         15
super_over            2
method                1
umpire1              62
umpire2              62
dtype: int64

In [13]:
df2.nunique()

match_id            1095
inning                 6
batting_team          19
bowling_team          19
over                  20
ball                  11
batter               673
bowler               530
non_striker          663
batsman_runs           7
extra_runs             7
total_runs             8
extras_type            5
is_wicket              2
player_dismissed     629
dismissal_kind        10
fielder              607
dtype: int64

In [14]:
df1.count()

id                 1095
season             1095
city               1044
date               1095
match_type         1095
player_of_match    1090
venue              1095
team1              1095
team2              1095
toss_winner        1095
toss_decision      1095
winner             1090
result             1095
result_margin      1076
target_runs        1092
target_overs       1092
super_over         1095
method               21
umpire1            1095
umpire2            1095
dtype: int64

In [15]:
df2.count()

match_id            260920
inning              260920
batting_team        260920
bowling_team        260920
over                260920
ball                260920
batter              260920
bowler              260920
non_striker         260920
batsman_runs        260920
extra_runs          260920
total_runs          260920
extras_type          14125
is_wicket           260920
player_dismissed     12950
dismissal_kind       12950
fielder               9354
dtype: int64

In [16]:
df1['player_of_match'].value_counts()

AB de Villiers       25
CH Gayle             22
RG Sharma            19
DA Warner            18
V Kohli              18
                     ..
NV Ojha               1
KV Sharma             1
Washington Sundar     1
PD Collingwood        1
Shahbaz Ahmed         1
Name: player_of_match, Length: 291, dtype: int64

In [17]:
df2['extras_type'].value_counts()

wides      8380
legbyes    4001
noballs    1069
byes        673
penalty       2
Name: extras_type, dtype: int64

In [18]:
df1.notnull().sum()

id                 1095
season             1095
city               1044
date               1095
match_type         1095
player_of_match    1090
venue              1095
team1              1095
team2              1095
toss_winner        1095
toss_decision      1095
winner             1090
result             1095
result_margin      1076
target_runs        1092
target_overs       1092
super_over         1095
method               21
umpire1            1095
umpire2            1095
dtype: int64

In [19]:
df2.notnull().sum()

match_id            260920
inning              260920
batting_team        260920
bowling_team        260920
over                260920
ball                260920
batter              260920
bowler              260920
non_striker         260920
batsman_runs        260920
extra_runs          260920
total_runs          260920
extras_type          14125
is_wicket           260920
player_dismissed     12950
dismissal_kind       12950
fielder               9354
dtype: int64

In [20]:
empty_venues = df1[df1['city'].isnull()]['venue'].unique()
empty_venues

array(['Sharjah Cricket Stadium', 'Dubai International Cricket Stadium'],
      dtype=object)

In [21]:
actual_city = df1[df1['venue'] == 'Dubai International Cricket Stadium']['city'].unique()
print(actual_city)
l = []
for i in range (2):
    if type(actual_city[i]) == str:
        l.append(actual_city[i])
print(l)

[nan 'Dubai']
['Dubai']

In [22]:
for i in range(len(empty_venues)):
    actual_city = df1[df1['venue'] == empty_venues[i]]['city'].unique()
    l = []
    print(actual_city)
    for j in range (len(actual_city)):
        if type(actual_city[j]) == str:
            l.append(actual_city[j])
            print(l)
    df1.loc[df1['venue'] == empty_venues[i],'city'] = l[0]
            
#df1.loc[df1['venue'] == 'Sharjah Cricket Stadium','city'] = 'Sharjah'

[nan 'Sharjah']
['Sharjah']
[nan 'Dubai']
['Dubai']

In [23]:
df1['city'].isnull().sum()

0

In [24]:
df1['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Rajkot', 'Kanpur', 'Bengaluru',
       'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'], dtype=object)

In [25]:
df1.loc[df1['venue'] == 'Sharjah Cricket Stadium','city']

399    Sharjah
404    Sharjah
406    Sharjah
408    Sharjah
413    Sharjah
414    Sharjah
759    Sharjah
764    Sharjah
771    Sharjah
773    Sharjah
778    Sharjah
783    Sharjah
786    Sharjah
788    Sharjah
796    Sharjah
801    Sharjah
806    Sharjah
811    Sharjah
850    Sharjah
852    Sharjah
856    Sharjah
859    Sharjah
862    Sharjah
863    Sharjah
866    Sharjah
869    Sharjah
873    Sharjah
874    Sharjah
Name: city, dtype: object

In [26]:
df1[df1['venue'] == 'Sharjah Cricket Stadium']['city']

399    Sharjah
404    Sharjah
406    Sharjah
408    Sharjah
413    Sharjah
414    Sharjah
759    Sharjah
764    Sharjah
771    Sharjah
773    Sharjah
778    Sharjah
783    Sharjah
786    Sharjah
788    Sharjah
796    Sharjah
801    Sharjah
806    Sharjah
811    Sharjah
850    Sharjah
852    Sharjah
856    Sharjah
859    Sharjah
862    Sharjah
863    Sharjah
866    Sharjah
869    Sharjah
873    Sharjah
874    Sharjah
Name: city, dtype: object

In [27]:
df1[df1['city'] == 'Sharjah'].count()

id                 28
season             28
city               28
date               28
match_type         28
player_of_match    28
venue              28
team1              28
team2              28
toss_winner        28
toss_decision      28
winner             28
result             28
result_margin      28
target_runs        28
target_overs       28
super_over         28
method              0
umpire1            28
umpire2            28
dtype: int64

In [28]:
df1[df1['city'] == 'Dubai'].count()

id                 46
season             46
city               46
date               46
match_type         46
player_of_match    46
venue              46
team1              46
team2              46
toss_winner        46
toss_decision      46
winner             46
result             46
result_margin      43
target_runs        46
target_overs       46
super_over         46
method              0
umpire1            46
umpire2            46
dtype: int64

In [29]:
df1['city'].isnull().sum()

0

In [30]:
df1.loc[(df1['result_margin'].isnull()) & (df1['result'] == 'tie'), 'result_margin'] = df1.loc[(df1['result_margin'].isnull()) & (df1['result'] == 'tie'), 'result_margin'].fillna(0.0)

In [31]:
df1['result_margin'].isnull().sum()

5

In [32]:
df1.loc[(df1['result_margin'].isnull())]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,NaN,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

In [33]:
df2[df2['match_id'] == 501265]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
57068,501265,1,Delhi Daredevils,Pune Warriors,0,1,NV Ojha,AC Thomas,DA Warner,1,0,1,NaN,0,NaN,NaN,NaN
57069,501265,1,Delhi Daredevils,Pune Warriors,0,2,DA Warner,AC Thomas,NV Ojha,0,1,1,legbyes,0,NaN,NaN,NaN
57070,501265,1,Delhi Daredevils,Pune Warriors,0,3,NV Ojha,AC Thomas,DA Warner,0,0,0,NaN,0,NaN,NaN,NaN
57071,501265,1,Delhi Daredevils,Pune Warriors,0,4,NV Ojha,AC Thomas,DA Warner,0,0,0,NaN,0,NaN,NaN,NaN
57072,501265,1,Delhi Daredevils,Pune Warriors,0,5,NV Ojha,AC Thomas,DA Warner,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57126,501265,1,Delhi Daredevils,Pune Warriors,9,4,CA Ingram,Yuvraj Singh,Y Venugopal Rao,0,1,1,noballs,0,NaN,NaN,NaN
57127,501265,1,Delhi Daredevils,Pune Warriors,9,5,CA Ingram,Yuvraj Singh,Y Venugopal Rao,4,0,4,NaN,0,NaN,NaN,NaN
57128,501265,1,Delhi Daredevils,Pune Warriors,9,6,CA Ingram,Yuvraj Singh,Y Venugopal Rao,1,0,1,NaN,0,NaN,NaN,NaN
57129,501265,1,Delhi Daredevils,Pune Warriors,9,7,Y Venugopal Rao,Yuvraj Singh,CA Ingram,0,0,0,NaN,0,NaN,NaN,NaN
57130,501265,1,Delhi Daredevils,Pune Warriors,10,1,CA Ingram,MR Marsh,Y Venugopal Rao,1,0,1,NaN,0,NaN,NaN,NaN

In [34]:
df1.loc[(df1['result_margin'].isnull()) & (df1['result'] == 'no result'), 'result_margin'] = df1.loc[(df1['result_margin'].isnull()) & (df1['result'] == 'no result'), 'result_margin'].fillna(0.0)

In [35]:
df1['result_margin'].isnull().sum()

0

In [36]:
df1.loc[(df1['target_runs'].isnull()) | (df1['target_overs'].isnull()), ['target_runs', 'target_overs']] = df1.loc[(df1['target_runs'].isnull()) | (df1['target_overs'].isnull()), ['target_runs', 'target_overs']].fillna(0.0)

In [37]:
df1[['target_runs','target_overs']].isnull().sum()

target_runs     0
target_overs    0
dtype: int64

In [38]:
df1.loc[(df1['player_of_match'].isnull()) | (df1['winner'].isnull())]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,0.0,0.0,0.0,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,0.0,0.0,0.0,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,0.0,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,NaN,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,0.0,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,0.0,0.0,0.0,N,NaN,AK Chaudhary,NA Patwardhan

In [39]:
df1.loc[(df1['player_of_match'].isnull()) | (df1['winner'].isnull()), ['player_of_match', 'winner']] = df1.loc[(df1['player_of_match'].isnull()) | (df1['winner'].isnull()), ['player_of_match', 'winner']].fillna('unable to decide')

In [40]:
df1[['player_of_match','winner']].isnull().sum()

player_of_match    0
winner             0
dtype: int64

In [41]:
df1['method'].unique()

array([nan, 'D/L'], dtype=object)

In [42]:
df1[df1['method'].notnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
38,336022,2007/08,Delhi,2008-05-17,League,DPMD Jayawardene,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Kings XI Punjab,runs,6.0,89.0,8.0,N,D/L,AV Jayaprakash,RE Koertzen
41,336025,2007/08,Kolkata,2008-05-18,League,M Ntini,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,runs,3.0,53.0,8.0,N,D/L,Asad Rauf,K Hariharan
60,392183,2009,Cape Town,2009-04-19,League,DL Vettori,Newlands,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,field,Delhi Daredevils,wickets,10.0,54.0,6.0,N,D/L,MR Benson,SD Ranade
63,392186,2009,Durban,2009-04-21,League,CH Gayle,Kingsmead,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,runs,11.0,69.0,9.2,N,D/L,DJ Harper,SD Ranade
89,392214,2009,Centurion,2009-05-07,League,ML Hayden,SuperSport Park,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,runs,12.0,187.0,18.0,N,D/L,DJ Harper,TH Wijewardene
192,501215,2011,Kochi,2011-04-18,League,BB McCullum,Nehru Stadium,Kochi Tuskers Kerala,Chennai Super Kings,Kochi Tuskers Kerala,field,Kochi Tuskers Kerala,wickets,7.0,135.0,17.0,N,D/L,K Hariharan,AL Hill
221,501245,2011,Kolkata,2011-05-07,League,Iqbal Abdulla,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Kolkata Knight Riders,runs,10.0,52.0,10.0,N,D/L,Asad Rauf,PR Reiffel
231,501255,2011,Bangalore,2011-05-14,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,4.0,102.0,13.0,N,D/L,RE Koertzen,RB Tiffin
429,733993,2014,Delhi,2014-05-10,League,DW Steyn,Feroz Shah Kotla,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,43.0,5.0,N,D/L,RM Deshpande,BNJ Oxenford
476,829743,2015,Visakhapatnam,2015-04-22,League,DA Warner,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Sunrisers Hyderabad,runs,16.0,118.0,12.0,N,D/L,RK Illingworth,VA Kulkarni
508,829807,2015,Hyderabad,2015-05-15,League,V Kohli,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,wickets,6.0,81.0,6.0,N,D/L,AK Chaudhary,HDPK Dharmasena
538,980943,2016,Hyderabad,2016-04-26,League,AB Dinda,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,runs,34.0,61.0,11.0,N,D/L,AY Dandekar,CK Nandan
561,980989,2016,Kolkata,2016-05-14,League,YK Pathan,Eden Gardens,Kolkata Knight Riders,Rising Pune Supergiants,Rising Pune Supergiants,bat,Kolkata Knight Riders,wickets,8.0,66.0,9.0,N,D/L,A Nand Kishore,BNJ Oxenford
565,980997,2016,Visakhapatnam,2016-05-17,League,AB Dinda,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Rising Pune Supergiants,Delhi Daredevils,Rising Pune Supergiants,field,Rising Pune Supergiants,runs,19.0,58.0,11.0,N,D/L,Nitin Menon,C Shamshuddin
566,980999,2016,Bangalore,2016-05-18,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,82.0,203.0,14.0,N,D/L,KN Ananthapadmanabhan,M Erasmus
633,1082648,2017,Bangalore,2017-05-17,Eliminator,NM Coulter-Nile,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,7.0,48.0,6.0,N,D/L,AK Chaudhary,Nitin Menon
641,1136566,2018,Jaipur,2018-04-11,League,SV Samson,Sawai Mansingh Stadium,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,Rajasthan Royals,runs,10.0,71.0,6.0,N,D/L,KN Ananthapadmanabhan,Nitin Menon
653,1136578,2018,Kolkata,2018-04-21,League,KL Rahul,Eden Gardens,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,9.0,125.0,13.0,N,D/L,A Deshmukh,C Shamshuddin
667,1136592,2018,Delhi,2018-05-02,League,RR Pant,Arun Jaitley Stadium,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,field,Delhi Daredevils,runs,4.0,151.0,12.0,N,D/L,CK Nandan,VK Sharma
951,1359476,2023,Chandigarh,2023-04-01,League,Arshdeep Singh,"Punjab Cricket Association IS Bindra Stadium, ...",Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Punjab Kings,runs,7.0,154.0,16.0,N,D/L,BNJ Oxenford,YC Barde
1023,1370353,2023,Ahmedabad,2023-05-29,Final,DP Conway,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,5.0,171.0,15.0,N,D/L,Nitin Menon,RJ Tucker

In [43]:
df1[df1['method'].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [44]:
df1.loc[(df1['method'].isnull()) & (df1['target_overs'] == 20.0)]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [45]:
df1.loc[(df1['method'].isnull()) & (df1['target_overs'] == 20.0), 'method'] = df1.loc[(df1['method'].isnull()) & (df1['target_overs'] == 20.0), 'method'].fillna('method N/R')

In [46]:
df1['method'].isnull().sum()

12

In [47]:
df1.loc[(df1['method'].isnull()) & (df1['target_overs'] != 20.0), 'method'] = df1.loc[(df1['method'].isnull()) & (df1['target_overs'] != 20.0), 'method'].fillna('no method')

In [48]:
df1['method'].isnull().sum()

0

In [49]:
df1.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [50]:
df1.isnull().sum().sum()

0

In [51]:
df2.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [52]:
df2['extras_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [53]:
df2[df2['extras_type'].isnull()]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [54]:
df2.loc[df2['extras_type'].isnull(), 'extras_type'] = df2.loc[df2['extras_type'].isnull(), 'extras_type'].fillna('no extras')

In [55]:
df2['extras_type'].isnull().sum()

0

In [56]:
df2.loc[(df2['player_dismissed'].isnull()) & (df2['dismissal_kind'].isnull()), ['player_dismissed', 'dismissal_kind']]

       player_dismissed dismissal_kind
0                   NaN            NaN
1                   NaN            NaN
2                   NaN            NaN
3                   NaN            NaN
4                   NaN            NaN
...                 ...            ...
260915              NaN            NaN
260916              NaN            NaN
260917              NaN            NaN
260918              NaN            NaN
260919              NaN            NaN

[247970 rows x 2 columns]

In [57]:
df2.loc[(df2['player_dismissed'].isnull()) & (df2['dismissal_kind'].isnull()), ['player_dismissed', 'dismissal_kind']].all()

player_dismissed    True
dismissal_kind      True
dtype: bool

In [58]:
df2.loc[(df2['player_dismissed'].isnull()) & (df2['dismissal_kind'].isnull()), ['player_dismissed', 'dismissal_kind']] = df2.loc[(df2['player_dismissed'].isnull()) & (df2['dismissal_kind'].isnull()), ['player_dismissed', 'dismissal_kind']].fillna('still batting')

In [59]:
df2.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type              0
is_wicket                0
player_dismissed         0
dismissal_kind           0
fielder             251566
dtype: int64

In [60]:
df2['fielder'].unique()

array([nan, 'JH Kallis', 'P Kumar', 'CL White', 'M Kartik', 'RT Ponting',
       'WP Saha', 'AB Agarkar', 'BB McCullum', 'KC Sangakkara',
       'IK Pathan', 'PA Patel', 'Joginder Sharma', 'P Amarnath',
       'M Manhas', 'B Geeves', 'V Kohli', 'Z Khan', 'MV Boucher',
       'AM Nayar', 'L Ronchi', 'LR Shukla', 'Mohammad Hafeez', 'AB Dinda',
       'DJ Hussey', 'SC Ganguly', 'RG Sharma', 'SB Styris', 'A Symonds',
       'Kamran Akmal', 'RA Jadeja', 'PP Chawla', 'S Dhawan', 'KD Karthik',
       'MK Tiwary', 'GD McGrath', 'G Gambhir', 'AC Gilchrist', 'DJ Bravo',
       'Harbhajan Singh', 'S Badrinath', 'JDP Oram', 'SK Raina',
       'D Salunkhe', 'SB Bangar', 'D Kalyankrishna', 'VVS Laxman',
       'DS Kulkarni', 'AM Rahane', 'A Nehra', 'B Lee', 'RR Sarwan',
       'Yuvraj Singh', 'MM Patel', 'GC Smith', 'M Rawat', 'Sohail Tanvir',
       'A Kumble', 'M Muralitharan', 'MS Dhoni', 'I Sharma', 'PP Ojha',
       'DPMD Jayawardene', 'V Sehwag', 'W Jaffer', 'R Vinay Kumar',
       'R Dravid', 'MEK Hussey', 'ST Jayasuriya', 'RV Uthappa', 'PR Shah',
       'LRPL Taylor', 'VY Mahesh', 'K Goel', 'S Sreesanth', 'SE Marsh',
       'Umar Gul', 'SK Trivedi', 'M Kaif', 'SR Watson', 'T Kohli',
       'Shoaib Malik', 'PJ Sangwan', 'SP Goswami', 'B Akhil', 'DW Steyn',
       'B Chipli', 'AS Yadav', 'LPC Silva', 'DB Ravi Teja', 'BJ Hodge',
       'DB Das', 'JR Hopes', 'AB de Villiers', 'SM Pollock', 'SS Tiwary',
       'DJ Thornely', 'SK Warne', 'M Ntini', 'U Kaul', 'DT Patil',
       'RP Singh', 'Shahid Afridi', 'HH Gibbs', 'YV Takawale',
       'YK Pathan', 'SA Asnodkar', 'CK Kapugedera', 'SR Tendulkar',
       'CRD Fernando', 'JA Morkel', 'SP Fleming', 'S Vidyut',
       'Salman Butt', 'A Chopra', 'NK Patel', 'MF Maharoof', 'TM Dilshan',
       'T Taibu', 'RR Raje', 'Younis Khan', 'WA Mota', 'LA Pomersbach',
       'RR Powar', 'Misbah-ul-Haq', 'MS Gony', 'R Bhatia', 'DR Smith',
       'TM Srivastava', 'VRV Singh', 'SD Chitnis', 'A Mukund',
       'Pankaj Singh', 'MK Pandey', 'L Balaji', 'ML Hayden', 'T Thushara',
       'R Ashwin', 'JD Ryder', 'DL Vettori', 'DP Nannes', 'Harmeet Singh',
       'MC Henriques', 'R Bishnoi', 'A Flintoff', 'CH Gayle',
       'Yashpal Singh', 'KP Pietersen', 'KV Sharma', 'Y Venugopal Rao',
       'DA Warner', 'Kamran Khan', 'AS Raut', 'RJ Quiney', 'RS Bopara',
       'A Mishra', 'Shoaib Ahmed', 'BAW Mendis', 'AN Ghosh', 'JP Duminy',
       'MN van Wyk', 'AD Mascarenhas', 'SL Malinga', 'SM Katich',
       'RE van der Merwe', 'VS Malik', 'SB Jakati', 'M Vijay',
       'SM Harwood', 'NV Ojha', 'RJ Harris', 'LA Carseldine', 'M Morkel',
       'TL Suman', 'AD Mathews', 'S Tyagi', 'S Sohal', 'Mashrafe Mortaza',
       'AM Salvi', 'SS Shaikh', 'J Botha', 'Mohammad Ashraful',
       'Anirudh Singh', 'P Dogra', 'R Sathish', 'MS Bisla', 'EJG Morgan',
       'FY Fazal', 'Y Nagar', 'AT Rayudu', 'AP Tare', 'JM Kemp',
       'Bipul Sharma', 'CA Pujara', 'AC Voges', 'KA Pollard',
       'WPUJC Vaas', 'GJ Bailey', 'J Theron', 'KP Appanna',
       'SJ Srivastava', 'MJ Lumb', 'AA Jhunjhunwala', 'SW Tait',
       'UT Yadav', 'R McLaren', 'S Ladda', 'KAJ Roach', 'S Narwal',
       'S Anirudha', 'DE Bollinger', 'PD Collingwood', 'AA Bilakhia',
       'AP Dole', 'Iqbal Abdulla', 'B Sumanth', 'MD Mishra', 'RS Sodhi',
       'AG Murtaza', 'JD Unadkat', 'MR Marsh', 'AG Paunikar',
       'AL Menaria', 'DJ Jacobs', 'JEC Franklin', 'R Sharma', 'IR Jaggi',
       'RN ten Doeschate', 'PC Valthaty', 'S Randiv', 'WD Parnell',
       'RV Gomez', 'DT Christian', 'MA Agarwal', 'R Ninan', 'Sunny Singh',
       'AJ Finch', 'SB Wagh', 'Shakib Al Hasan', 'NLTC Perera',
       'AC Thomas', 'KM Jadhav', 'DH Yagnik', 'STR Binny', 'NL McCullum',
       'A Mithun', 'Harpreet Singh', 'J Syed Mohammad', 'F du Plessis',
       'AC Blizzard', 'AUK Pathan', 'KB Arun Karthik', 'B Kumar',
       'CJ Ferguson', 'Mandeep Singh', 'OA Shah', 'Y Gnaneswara Rao',
       'AA Chavan', 'Anand Rajan', 'KH Devdhar', 'AN Ahmed', 'S Aravind',
       'JP Faulkner', 'KK Cooper', 'A Singh', 'DAJ Bracewell', 'HV Patel',
       'DJ Harris', 'SPD Smith', 'RE Levi', 'RR Bhatkal', 'P Awana',
       'S Nadeem', 'T Mishra', 'KMDN Kulasekara', 'N Saini', 'DA Miller',
       'LJ Wright', 'Azhar Mahmood', 'GB Hogg', 'RJ Peterson',
       'Gurkeerat Singh', 'MJ Clarke', 'A Ashish Reddy', 'P Negi',
       'VR Aaron', 'CA Lynn', 'A Chandila', 'UBT Chand', 'SP Narine',
       'MG Johnson', 'MN Samuels', 'Ankit Sharma', 'Mohammed Shami',
       'R Shukla', 'BMAJ Mendis', 'R Dhawan', 'CH Morris', 'KL Rahul',
       'PA Reddy', 'GH Vihari', 'SV Samson', 'BB Samantray', 'Q de Kock',
       'MM Sharma', 'SMSM Senanayake', 'R Rampaul', 'AD Russell',
       'M Vohra', 'S Kaul', 'BJ Rohrer', 'DJG Sammy', 'P Suyal',
       'UA Birla', 'Sachin Baby', 'JO Holder', 'K Upadhyay', 'GJ Maxwell',
       'NM Coulter-Nile', 'AR Patel', 'CJ Anderson', 'KW Richardson',
       'YS Chahal', 'NJ Maddinson', 'S Rana', 'BW Hilfenhaus', 'MA Starc',
       'CM Gautam', 'TG Southee', 'AV Wankhade', 'IC Pandey', 'SA Yadav',
       'KK Nair', 'BR Dunk', 'LMP Simmons', 'RR Rossouw', 'Shivam Sharma',
       'BCJ Cutting', 'K Santokie', 'BE Hendricks', 'Parvez Rasool',
       'Sandeep Sharma', 'Karanveer Singh', 'SS Iyer', 'TA Boult',
       'J Suchith', 'KS Williamson', 'PJ Cummins', 'RG More',
       'Anureet Singh', 'Imran Tahir', 'R Tewatia', 'J Yadav', 'D Wiese',
       'HH Pandya', 'DJ Hooda', 'B Aparajith', 'MJ McClenaghan',
       'SN Khan', 'AF Milne', 'C Munro', 'CR Brathwaite', 'KH Pandya',
       'Mustafizur Rahman', 'NS Naik', 'JC Buttler', 'PV Tambe',
       'BB Sran', 'Ishan Kishan', 'KC Cariappa', 'RR Pant', 'SW Billings',
       'V Shankar', 'JJ Bumrah', 'UT Khawaja', 'CJ Jordan', 'ER Dwivedi',
       'AS Rajpoot', 'DL Chahar', 'F Behardien', 'Kuldeep Yadav',
       'N Rana', 'MP Stoinis', 'BA Stokes', 'B Stanlake', 'Rashid Khan',
       'CR Woakes', 'RD Chahar', 'C de Grandhomme', 'JJ Roy',
       'RA Tripathi', 'K Rabada', 'Basil Thampi', 'S Badree', 'TS Mills',
       'Washington Sundar', 'SN Thakur', 'SP Jackson', 'LH Ferguson',
       'TM Head', 'Ankit Soni', 'Mohammed Siraj', 'R Powell',
       'MJ Guptill', 'Vishnu Vinod', 'MA Wood', 'E Lewis', 'AJ Tye',
       'RK Singh', 'B Laughlin', 'Shivam Mavi', 'K Gowtham',
       'Mujeeb Ur Rahman', 'DJM Short', 'TK Curran', 'H Klaasen',
       'Avesh Khan', 'LE Plunkett', 'PP Shaw', 'M Markande', 'AD Hales',
       'Shubman Gill', 'DJ Willey', 'AD Nath', 'JPR Scantlebury-Searles',
       'M Prasidh Krishna', 'Abhishek Sharma', 'MM Ali', 'JC Archer',
       'DR Shorey', 'S Dube', 'Rasikh Salam', 'SO Hetmyer',
       'Navdeep Saini', 'P Chopra', 'M Ashwin', 'JM Bairstow',
       'Mohammad Nabi', 'SM Curran', 'S Lamichhane', 'CA Ingram',
       'S Midhun', 'S Gopal', 'KMA Paul', 'Milind Kumar', 'N Pooran',
       'SE Rutherford', 'R Parag', 'MJ Santner', 'P Simran Singh',
       'LS Livingstone', 'MK Lomror', 'O Thomas', 'S Sandeep Warrier',
       'Anmolpreet Singh', 'JL Pattinson', 'D Padikkal', 'PK Garg',
       'TU Deshpande', 'KL Nagarkoti', 'KK Ahmed', 'YBK Jaiswal',
       'I Udana', 'JDS Neesham', 'CV Varun', 'RD Gaikwad', 'A Nortje',
       'AT Carey', 'Ravi Bishnoi', 'AS Roy', 'Abdul Samad',
       'Shahbaz Ahmed', 'CJ Green', 'T Natarajan', 'Arshdeep Singh',
       'Kartik Tyagi', 'Lalit Yadav', 'DR Sams', 'A Zampa', 'P Dubey',
       'C Sakariya', 'M Jansen', 'M Shahrukh Khan', 'Virat Singh',
       'RV Patel', 'JA Richardson', 'L Ngidi', 'FA Allen', 'KA Jamieson',
       'RM Patidar', 'Harpreet Brar', 'Anuj Rawat', 'DJ Malan',
       'GD Phillips', 'JR Hazlewood', 'VR Iyer', 'GHS Garton',
       'KS Bharat', 'AK Markram', 'TL Seifert', 'Tilak Varma', 'TH David',
       'MS Wade', 'Akash Deep', 'OF Smith', 'A Manohar', 'D Pretorius',
       'JM Sharma', 'A Badoni', 'D Brevis', 'Umran Malik',
       'Ramandeep Singh', 'B Sai Sudharsan', 'SS Prabhudessai',
       'VG Arora', 'HE van der Dussen', 'Shashank Singh', 'PVD Chameera',
       'PWH de Silva', 'NT Ellis', 'Mukesh Choudhary', 'RP Meredith',
       'HR Shokeen', 'KR Sen', 'AS Joseph', 'B Indrajith', 'DJ Mitchell',
       'Simarjeet Singh', 'DP Conway', 'PBB Rajapaksa', 'R Sai Kishore',
       'Yash Dayal', 'M Pathirana', 'PN Mankad', 'Mohsin Khan',
       'OC McCoy', 'Rahmanullah Gurbaz', 'Sikandar Raza', 'KR Mayers',
       'Fazalhaq Farooqi', 'KM Asif', 'Yash Thakur', 'J Little',
       'Abishek Porel', 'MW Short', 'N Jagadeesan', 'C Green',
       'JP Behrendorff', 'N Wadhera', 'Arshad Khan', 'Mukesh Kumar',
       'SSB Magala', 'Aman Hakim Khan', 'YV Dhull', 'D Jansen',
       'M Theekshana', 'Atharva Taide', 'Akash Singh', 'Naveen-ul-Haq',
       'HC Brook', 'PD Salt', 'Vijaykumar Vyshak', 'Harshit Rana',
       'SK Rasheed', 'Sonu Yadav', 'R Goyal', 'Noor Ahmad', 'JE Root',
       'Dhruv Jurel', 'MG Bracewell', 'MD Shanaka', 'D Ferreira',
       'K Kartikeya', 'Nithish Kumar Reddy', 'Subhransu Senapati',
       'R Ravindra', 'Tanay Thyagarajan', 'Suyash Sharma', 'N Burger',
       'Naman Dhir', 'Sameer Rizvi', 'T Stubbs', 'DG Nalkande',
       'Mayank Dagar', 'J Fraser-McGurk', 'BR Sharath', 'Akash Madhwal',
       'RJW Topley', 'Tanush Kotian', 'KA Maharaj', 'A Raghuvanshi',
       'Sumit Kumar', 'SH Johnson', 'Ashutosh Sharma', 'SD Hope',
       'LB Williams', 'MP Yadav', 'N Thushara', 'G Coetzee',
       'Swapnil Singh', 'A Kamboj', 'Sanvir Singh', 'WG Jacks',
       'Kumar Kushagra', 'Gulbadin Naib', 'Shivam Singh', 'V Viyaskanth',
       'T Kohler-Cadmore'], dtype=object)

In [61]:
df2.loc[df2['fielder'].isnull()]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,still batting,still batting,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,no extras,0,still batting,still batting,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,still batting,still batting,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,no extras,0,still batting,still batting,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,no extras,0,still batting,still batting,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,no extras,0,still batting,still batting,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,no extras,0,still batting,still batting,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,no extras,0,still batting,still batting,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,no extras,0,still batting,still batting,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,no extras,0,still batting,still batting,NaN

In [62]:
df2.loc[df2['fielder'].isnull(), 'fielder'] = df2.loc[df2['fielder'].isnull(), 'fielder'].fillna('not involved')

In [63]:
df2.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [64]:
df2.isnull().sum().sum()

0

In [65]:
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [66]:
len(df1.columns)

20

In [67]:
first = list(df1.columns)
first

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2']

In [68]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [69]:
len(df2.columns)

17

In [70]:
second = list(df2.columns)
second

['match_id',
 'inning',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'batter',
 'bowler',
 'non_striker',
 'batsman_runs',
 'extra_runs',
 'total_runs',
 'extras_type',
 'is_wicket',
 'player_dismissed',
 'dismissal_kind',
 'fielder']

In [71]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\user\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [72]:
from openpyxl import Workbook

In [ ]:
wb = Workbook()
sheet = wb.active

# Headers

L1 = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T']

for i in range(len(L1)):
    sheet[f"{L1[i]}1"] = first[i]



# Write data
for i in range(len(df1)):
    sheet[f"A{i+2}"] = df1["id"].iloc[i]
    sheet[f"B{i+2}"] = df1["season"].iloc[i]
    sheet[f"C{i+2}"] = df1["city"].iloc[i]
    sheet[f"D{i+2}"] = df1["date"].iloc[i]
    sheet[f"E{i+2}"] = df1["match_type"].iloc[i]
    sheet[f"F{i+2}"] = df1["player_of_match"].iloc[i]
    sheet[f"G{i+2}"] = df1["venue"].iloc[i]
    sheet[f"H{i+2}"] = df1["team1"].iloc[i]
    sheet[f"I{i+2}"] = df1["team2"].iloc[i]
    sheet[f"J{i+2}"] = df1["toss_winner"].iloc[i]
    sheet[f"K{i+2}"] = df1["toss_decision"].iloc[i]
    sheet[f"L{i+2}"] = df1["winner"].iloc[i]
    sheet[f"M{i+2}"] = df1["result"].iloc[i]
    sheet[f"N{i+2}"] = df1["result_margin"].iloc[i]
    sheet[f"O{i+2}"] = df1["target_runs"].iloc[i]
    sheet[f"P{i+2}"] = df1["target_overs"].iloc[i]
    sheet[f"Q{i+2}"] = df1["super_over"].iloc[i]
    sheet[f"R{i+2}"] = df1["method"].iloc[i]
    sheet[f"S{i+2}"] = df1["umpire1"].iloc[i]
    sheet[f"T{i+2}"] = df1["umpire2"].iloc[i]

wb.save("Matches_Final_dataset.xlsx")

In [73]:

wb = Workbook()
sheet = wb.active

# Headers

L2 = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q']

for j in range(len(L2)):
    sheet[f"{L2[j]}1"] = second[j]



# Write data
for i in range(len(df2)):
    sheet[f"A{i+2}"] = df2["match_id"].iloc[i]
    sheet[f"B{i+2}"] = df2["inning"].iloc[i]
    sheet[f"C{i+2}"] = df2["batting_team"].iloc[i]
    sheet[f"D{i+2}"] = df2["bowling_team"].iloc[i]
    sheet[f"E{i+2}"] = df2["over"].iloc[i]
    sheet[f"F{i+2}"] = df2["ball"].iloc[i]
    sheet[f"G{i+2}"] = df2["batter"].iloc[i]
    sheet[f"H{i+2}"] = df2["bowler"].iloc[i]
    sheet[f"I{i+2}"] = df2["non_striker"].iloc[i]
    sheet[f"J{i+2}"] = df2["batsman_runs"].iloc[i]
    sheet[f"K{i+2}"] = df2["extra_runs"].iloc[i]
    sheet[f"L{i+2}"] = df2["total_runs"].iloc[i]
    sheet[f"M{i+2}"] = df2["extras_type"].iloc[i]
    sheet[f"N{i+2}"] = df2["is_wicket"].iloc[i]
    sheet[f"O{i+2}"] = df2["player_dismissed"].iloc[i]
    sheet[f"P{i+2}"] = df2["dismissal_kind"].iloc[i]
    sheet[f"Q{i+2}"] = df2["fielder"].iloc[i]

wb.save("Deliveries_Final_Dataset.xlsx")